// Generated by Wrangler on Sat Feb 11 2023 05:00:43 GMT+0100 (Central European Standard Time)
interface Env {
	OPENAI_API_KEY: string;
	PROMPTSTUDIO_PROXY_ID: '3479a61a-9d8b-4884-99b5-02933833e6f3';
}
declare module '*.html' {
	const value: ArrayBuffer;
	export default value;
}
